const container = document.querySelector(".container");
const APIURL =
  "https://api.unsplash.com/photos/?client_id=dX-JVkeQ_txGnosc-DbeaD5D0vE3v_tpqepAiebftyk";

const row = 5;
apiCall();

async function apiCall() {
  let res = await fetch(APIURL);
  let data = await res.json();
  console.log(data);
  generateImage(data);
}
function generateImage(data) {
  data.forEach((x) => {
    const divel = document.createElement("div");
    divel.classList.add("img-cont");
    divel.innerHTML = `<img src='${x.urls.small}' alt='Random image generated by unsplash'>`;
    container.appendChild(divel);
  });
  // for (let i = 0; i < data.length; i++) {
  //   console.log(data.length);
  //   console.log(i.urls);
  //
  // }
}

function getRandomSize() {
  return `${getRandomNum()}x${getRandomNum()}`;
}

function getRandomNum() {
  return Math.floor(Math.random() * 10) + 300;
}
